name: first

on: push

jobs:
  job1:
    name: ubuntu job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: |
        git config --global user.email "alantuneit@gmail.com"
        git config --global user.name "Alan Cole"
        git branch
        touch newFile.txt
        echo "new file > newFile.txt"
        git add .
        git commit -m "adding newFile.txt"
        git push origin $GITHUB_REF

  job2:
    name: windows job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildItem Env: | Sort-Object Name"

